spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 5000
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1
  datasource:
    druid:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://127.0.0.1:3306/liuyuequn?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456

      initial-size: 5
      min-idle: 5
      max-active: 31
      max-wait: 5000
      time-between-eviction-runs-millis: 90000
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
jwt:
  header: Authorization
  secret: mySecret
  #24小时
  expiration: 864000000
server:
  port: 10086
